import { expect, test } from "@playwright/test";
import { eq } from "drizzle-orm";
import { catalogRelease, catalogReleaseRule, climateDatasetVersion, createDatabase, crop, cropVariety, evidenceItem, garden, knowledgeSource, organization, ruleFamily, ruleVersion } from "../../packages/db/src/index.js";

const appURL = process.env.APP_URL ?? "http://localhost:42069";

async function seedPlanningCatalog() {
  const connectionString = process.env.TRESTLE_BROWSER_DATABASE_URL; if (!connectionString) throw new Error("Browser database is required");
  const database = createDatabase(connectionString, "postgres-js"); const nonce = crypto.randomUUID(); const cropId = crypto.randomUUID(); const varietyId = crypto.randomUUID(); const sourceId = crypto.randomUUID(); const evidenceId = crypto.randomUUID(); const familyIds = [crypto.randomUUID(), crypto.randomUUID(), crypto.randomUUID()]; const ruleIds = [crypto.randomUUID(), crypto.randomUUID(), crypto.randomUUID()]; const releaseId = crypto.randomUUID();
  await database.insert(crop).values({ id: cropId, slug: `browser-crop-${nonce}`, commonName: "Browser fixture tomato", status: "published" });
  await database.insert(cropVariety).values({ id: varietyId, cropId, name: "Browser fixture slicer", normalizedName: `browser-fixture-slicer-${nonce}`, status: "published" });
  await database.insert(knowledgeSource).values({ id: sourceId, url: `https://example.test/browser-${nonce}`, title: "Browser fixture", publisher: "Tests", sourceType: "fixture", accessedAt: new Date() });
  await database.insert(evidenceItem).values({ id: evidenceId, sourceId, normalizedClaim: "Synthetic browser fact", scope: { fixture: true } });
  await database.insert(ruleFamily).values([{ id: familyIds[0]!, cropId, ruleType: "spacing", method: "direct_sow", contextKey: nonce }, { id: familyIds[1]!, cropId, ruleType: "planting_window", method: "direct_sow", contextKey: nonce }, { id: familyIds[2]!, cropId, ruleType: "maturity", method: "direct_sow", contextKey: nonce }]);
  const applicability = { methods: ["direct_sow"], regionIds: [], climateRegimes: [], hardinessZones: [], varietyIds: [] };
  await database.insert(ruleVersion).values([{ id: ruleIds[0]!, familyId: familyIds[0]!, version: 1, state: "published", applicability, payload: { state: "known", type: "spacing", withinRowMeters: { minimum: 0.5, maximum: 0.5, minimumInclusive: true, maximumInclusive: true }, pattern: "individual", sourceUnit: "meters" }, evidenceIds: [evidenceId], publishedAt: new Date() }, { id: ruleIds[1]!, familyId: familyIds[1]!, version: 1, state: "published", applicability, payload: { state: "known", type: "planting_window", windows: [{ kind: "calendar", startMonth: 3, startDay: 1, endMonth: 4, endDay: 15, endYearOffset: 0 }, { kind: "calendar", startMonth: 5, startDay: 1, endMonth: 5, endDay: 15, endYearOffset: 0 }, { kind: "calendar", startMonth: 7, startDay: 1, endMonth: 7, endDay: 15, endYearOffset: 0 }] }, evidenceIds: [evidenceId], publishedAt: new Date() }, { id: ruleIds[2]!, familyId: familyIds[2]!, version: 1, state: "published", applicability, payload: { state: "known", type: "maturity", days: { minimum: 50, maximum: 60, minimumInclusive: true, maximumInclusive: true }, anchor: "sowing", sourceUnit: "calendar_days" }, evidenceIds: [evidenceId], publishedAt: new Date() }]);
  await database.insert(catalogRelease).values({ id: releaseId, name: `browser-${nonce}`, status: "published", publishedBy: "browser-test", publishedAt: new Date() }); await database.insert(catalogReleaseRule).values(ruleIds.map((ruleVersionId) => ({ releaseId, ruleVersionId })));
  await database.insert(climateDatasetVersion).values({ kind: "frost_hardiness", sourceName: "Browser fixture", sourceRelease: nonce, sourceUrl: "https://example.test/climate", checksumSha256: nonce.padEnd(64, "0"), normalizationVersion: 1, attribution: "Synthetic browser fixture", coverage: { fixture: true }, status: "published", recordCount: 1, publishedAt: new Date() });
  await database.$client.end();
}

test("a new gardener receives one private workspace and can save the garden", async ({ page }, testInfo) => {
  await seedPlanningCatalog();
  const readiness = await page.request.get(`${appURL}/api/health/product`);
  expect(readiness.status()).toBe(200);
  await expect(readiness.json()).resolves.toMatchObject({ status: "ready", missing: [] });
  const nonce = crypto.randomUUID().slice(0, 12);
  const email = `garden-${nonce}@example.test`;
  const password = `Garden-test-${nonce}!`;

  await page.goto("/sign-up");
  await page.getByRole("textbox", { name: "Name" }).fill("Garden Tester");
  await page.getByRole("textbox", { name: "Email" }).fill(email);
  await page.getByLabel("Password").fill(password);
  await page.getByRole("button", { name: "Create account" }).click();
  await expect(page.getByRole("heading", { name: "Check your email" })).toBeVisible();
  const message = page.locator("article").filter({ hasText: email });
  const verificationUrl = await message.getByRole("link", { name: "Open message link" }).getAttribute("href");
  expect(verificationUrl).toBeTruthy();
  await page.goto(verificationUrl!);

  await page.goto("/sign-in");
  await page.getByRole("textbox", { name: "Email" }).fill(email);
  await page.getByLabel("Password").fill(password);
  await page.getByRole("button", { name: "Sign in" }).click();
  await expect(page.getByRole("heading", { name: "Hello, Garden Tester" })).toBeVisible();
  await expect(page.getByText(/organization/iu)).toHaveCount(0);
  await expect(page.getByRole("combobox", { name: /organization/iu })).toHaveCount(0);

  await page.getByRole("link", { name: "Open my garden" }).click();
  await expect(page.getByRole("heading", { name: "Garden basics" })).toBeVisible();
  await page.getByLabel("Garden name").fill("Kitchen Garden");
  await page.getByRole("button", { name: "Save garden" }).click();
  await expect(page.getByText("Saved", { exact: true })).toBeVisible();
  await expect(page.getByText("The aerial map is unavailable in this environment.", { exact: false })).toBeVisible();
  await page.getByLabel("Latitude").fill("34.0522");
  await page.getByLabel("Longitude").fill("-118.2437");
  await page.getByLabel("Time zone").fill("America/Los_Angeles");
  await page.getByRole("button", { name: "Confirm this garden pin" }).click();
  await expect(page.getByText("Location confirmed. Climate matching has been refreshed.")).toBeVisible();
  await page.getByLabel("Hardiness zone").fill("10b");
  await page.getByLabel("Last spring frost (MM-DD)").fill("02-15");
  await page.getByLabel("First autumn frost (MM-DD)").fill("12-01");
  await page.getByRole("button", { name: "Use these dates" }).click();
  await expect(page.getByText("Your seasonal anchor has been saved as gardener-supplied information.")).toBeVisible();
  await page.reload();
  await expect(page.getByLabel("Garden name")).toHaveValue("Kitchen Garden");
  await expect(page.getByLabel("Latitude")).toHaveValue("34.0522");
  await expect(page.getByText("Pin confirmed", { exact: true })).toBeVisible();
  await expect(page.getByText("Status:", { exact: false })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Draw your growing space" })).toBeVisible();
  await page.getByRole("button", { name: "Pan view" }).click();
  await expect(page.getByRole("button", { name: "Outer boundary vertex 1", exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Reset view" }).click();
  await page.getByRole("button", { name: "Edit shape" }).click();
  await page.getByRole("button", { name: "Insert vertex after outer boundary vertex 1" }).press("Enter");
  await expect(page.getByLabel("Outer boundary vertex 5 X")).toBeVisible();
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  await page.getByRole("button", { name: "Draw new boundary" }).click();
  const closePolygon = page.getByRole("button", { name: "Close polygon" });
  await expect(closePolygon).toBeDisabled();
  const preview = page.getByRole("img", { name: "Interactive metric bed preview" });
  await preview.scrollIntoViewIfNeeded();
  const previewBox = await preview.boundingBox();
  expect(previewBox).not.toBeNull();
  const addDrawPoint = async (x: number, y: number) => testInfo.project.use.hasTouch ? await preview.dispatchEvent("touchend", { touches: [], targetTouches: [], changedTouches: [{ identifier: 0, clientX: previewBox!.x + x, clientY: previewBox!.y + y }] }) : await page.mouse.click(previewBox!.x + x, previewBox!.y + y);
  await addDrawPoint(60, 60);
  await addDrawPoint(260, 60);
  await addDrawPoint(160, 160);
  await expect(closePolygon).toBeEnabled();
  await closePolygon.click();
  await expect(page.getByLabel("Outer boundary vertex 4 X")).toHaveCount(0);
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  await expect(page.getByLabel("Outer boundary vertex 4 X")).toBeVisible();
  const vertex = page.getByRole("button", { name: "Outer boundary vertex 2", exact: true });
  await vertex.focus();
  await vertex.press("Shift+ArrowRight");
  await expect(page.getByLabel("Outer boundary vertex 2 X")).toHaveValue("3.5");
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  await expect(page.getByLabel("Outer boundary vertex 2 X")).toHaveValue("3");
  if (!testInfo.project.use.hasTouch) {
    const vertexBox = await vertex.boundingBox();
    expect(vertexBox).not.toBeNull();
    await page.mouse.move(vertexBox!.x + vertexBox!.width / 2, vertexBox!.y + vertexBox!.height / 2);
    await page.mouse.down();
    await page.mouse.move(vertexBox!.x + vertexBox!.width / 2 + 24, vertexBox!.y + vertexBox!.height / 2);
    await page.mouse.up();
    await expect(page.getByLabel("Outer boundary vertex 2 X")).not.toHaveValue("3");
    await page.getByRole("button", { name: "Undo", exact: true }).click();
    await expect(page.getByLabel("Outer boundary vertex 2 X")).toHaveValue("3");
  }
  await page.getByRole("button", { name: "Add exclusion" }).click();
  await expect(page.getByLabel("Exclusion 1 vertex 1 X")).toBeVisible();
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  await expect(page.getByLabel("Exclusion 1 vertex 1 X")).toHaveCount(0);
  await page.getByRole("button", { name: "Redo", exact: true }).click();
  await page.getByRole("button", { name: "Remove exclusion 1" }).click();
  await expect(page.getByLabel("Exclusion 1 vertex 1 X")).toHaveCount(0);
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  await expect(page.getByLabel("Exclusion 1 vertex 1 X")).toBeVisible();
  await page.getByLabel("Sunlight condition").selectOption("full_sun");
  await page.getByLabel("Sunlight observed hours").fill("7");
  await page.getByLabel("Bed rotation degrees").fill("15");
  await page.getByLabel("Bed translation X").fill("0.5");
  await page.getByLabel("Bed translation Y").fill("-0.25");
  await page.getByRole("button", { name: "Save bed", exact: true }).click();
  await expect(page.getByText("Bed revision saved.")).toBeVisible();
  await expect(page.getByRole("button", { name: "Main bed · revision 1" })).toBeVisible();
  await page.getByRole("button", { name: "Main bed · revision 1" }).click();
  await expect(page.getByLabel("Bed rotation degrees")).toHaveValue("15");
  await expect(page.getByLabel("Bed translation X")).toHaveValue("0.5");
  await expect(page.getByLabel("Bed translation Y")).toHaveValue("-0.25");
  await page.getByLabel("Outer boundary vertex 2 X").fill("4");
  await page.getByRole("button", { name: "Save new revision" }).click();
  await expect(page.getByRole("button", { name: "Main bed · revision 2" })).toBeVisible();
  const printHref = await page.getByRole("link", { name: "Print diagram" }).getAttribute("href");
  expect(printHref).toContain("print.svg");
  await expect(page.getByRole("heading", { name: "Build a planting proposal" })).toBeVisible();
  await expect(page.getByLabel("Crop")).toContainText("Browser fixture tomato");
  await page.getByLabel("Variety").selectOption({ label: "Browser fixture slicer" });
  await page.getByRole("button", { name: "Add crop" }).click();
  await expect(page.getByText(/Browser fixture tomato · Browser fixture slicer: 4 retained plants/u)).toBeVisible();
  await page.getByRole("button", { name: "Generate proposal" }).click();
  await expect(page.getByText(/4 placed, 0 unplaced/u)).toBeVisible();
  await expect(page.getByText("Why these rules were used", { exact: true })).toBeVisible();
  await expect(page.getByText(/through/u).first()).toBeVisible();
  await page.getByRole("button", { name: "Save pinned position" }).click();
  await expect(page.getByRole("heading", { name: /Plan version 2 · proposal/u })).toBeVisible();
  await page.getByRole("button", { name: "Activate this plan" }).click();
  await expect(page.getByRole("heading", { name: /active/u })).toBeVisible();
  await expect(page.getByRole("heading", { name: "This week" })).toBeVisible();
  await expect(page.getByText(/Sow in the planned position/u).first()).toBeVisible();
  await page.getByLabel("Progress date").fill(`${new Date().getFullYear()}-03-10`);
  await page.getByRole("button", { name: "Record progress" }).click();
  await expect(page.getByText(/sown/u).last()).toBeVisible();
  await expect(page.getByText(/recalculated from an actual event/u)).toBeVisible();
  await page.getByRole("button", { name: "Correct" }).first().click();
  await page.getByLabel("Correction date").fill(`${new Date().getFullYear()}-03-11`);
  await page.getByLabel("Correction reason").fill("Corrected my notebook date");
  await page.getByRole("button", { name: "Save correction" }).click();
  await expect(page.getByText(/correction \(correction\)/u)).toBeVisible();
  await page.getByRole("button", { name: "Complete" }).first().click();
  await expect(page.getByText(/task completed/u)).toBeVisible();
  await page.getByRole("button", { name: "Postpone one week" }).first().click();
  await expect(page.getByText(/task postponed/u)).toBeVisible();
  await page.getByRole("button", { name: "Skip" }).first().click();
  await expect(page.getByText(/task skipped/u)).toBeVisible();
  await expect(page.getByRole("group", { name: "Email choices" })).toBeVisible();
  await page.getByLabel("Use quiet hours").check();
  await expect(page.getByLabel("Quiet hours start")).toHaveValue("22:00");
  await page.getByLabel("Allow urgent protection warnings during quiet hours").uncheck();
  await page.getByRole("button", { name: "Save email choices" }).click();
  await expect(page.getByText("Notification choices saved.")).toBeVisible();

  const bootstrap = await page.context().request.post(`${appURL}/api/workspace/bootstrap`, { headers: { origin: appURL } });
  const workspace = (await bootstrap.json() as { workspace: { organizationId: string } }).workspace;
  const subscription = await page.context().request.get(`${appURL}/api/billing/subscription`, { headers: { "x-trestle-tenant": workspace.organizationId } });
  expect(subscription.status()).toBe(200);
  const free = await subscription.json() as { subscription: unknown; access: { plan: string } };
  expect(free.subscription).toBeNull();
  expect(free.access.plan).toBe("free");

  await page.getByRole("link", { name: "Plan", exact: true }).click();
  await expect(page.getByText("Current access:")).toContainText("free");
  await page.getByRole("button", { name: "Continue to Pro checkout" }).click();
  await expect(page.getByText("Current access:")).toContainText("pro");
  await expect(page.getByText("Forecast monitoring and frost-risk alerts")).toBeVisible();
  await page.getByRole("button", { name: "Cancel Pro" }).click();
  await expect(page.getByText("Current access:")).toContainText("free");
  await expect(page.getByText(/garden, plan and history remain available/u)).toBeVisible();
  await page.getByRole("link", { name: "My garden" }).click();
  await expect(page.getByLabel("Garden name")).toHaveValue("Kitchen Garden");

  await page.goto("/dashboard");
  await page.getByLabel("Confirm with your password").fill(password);
  await page.getByRole("button", { name: "Permanently delete account" }).click();
  await expect(page.getByRole("heading", { name: "A garden plan built around your yard." })).toBeVisible();
  const connectionString = process.env.TRESTLE_BROWSER_DATABASE_URL; if (!connectionString) throw new Error("Browser database is required");
  const database = createDatabase(connectionString, "postgres-js");
  expect(await database.select({ id: organization.id }).from(organization).where(eq(organization.id, workspace.organizationId))).toEqual([]);
  expect(await database.select({ id: garden.id }).from(garden).where(eq(garden.organizationId, workspace.organizationId))).toEqual([]);
  await database.$client.end();
});
