import { sql } from "drizzle-orm";
import { boolean, check, foreignKey, index, integer, jsonb, pgPolicy, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { organization } from "./auth-schema.js";
import { garden } from "./garden-schema.js";

export const weatherLocationDue = pgTable("weather_location_due", {
  gardenId: uuid("garden_id").primaryKey(), organizationId: text("organization_id").notNull().references(() => organization.id, { onDelete: "cascade" }), locationRevision: integer("location_revision").notNull(), nextDueAt: timestamp("next_due_at", { withTimezone: true }).notNull(), leaseToken: uuid("lease_token"), leaseExpiresAt: timestamp("lease_expires_at", { withTimezone: true }), lastSucceededAt: timestamp("last_succeeded_at", { withTimezone: true }), failureCount: integer("failure_count").default(0).notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [uniqueIndex("weather_location_due_tenant_key").on(table.organizationId, table.gardenId), index("weather_location_due_next_idx").on(table.nextDueAt), foreignKey({ columns: [table.organizationId, table.gardenId], foreignColumns: [garden.organizationId, garden.id], name: "weather_location_due_tenant_garden_fk" }).onDelete("cascade"), check("weather_location_due_revision_check", sql`${table.locationRevision} > 0`), pgPolicy("weather_location_due_tenant", { for: "all", to: "trestle_app", using: sql`${table.organizationId} = current_setting('app.organization_id', true)`, withCheck: sql`${table.organizationId} = current_setting('app.organization_id', true)` }), pgPolicy("weather_location_due_platform", { for: "all", to: "trestle_platform", using: sql`true`, withCheck: sql`true` })]).enableRLS();

export const weatherForecastSnapshot = pgTable("weather_forecast_snapshot", {
  id: uuid("id").defaultRandom().primaryKey(), provider: text("provider").notNull(), sourceKey: text("source_key").notNull(), sourceUpdatedAt: timestamp("source_updated_at", { withTimezone: true }).notNull(), retrievedAt: timestamp("retrieved_at", { withTimezone: true }).notNull(), validFrom: timestamp("valid_from", { withTimezone: true }).notNull(), validThrough: timestamp("valid_through", { withTimezone: true }).notNull(), fingerprint: text("fingerprint").notNull(), normalizationVersion: integer("normalization_version").notNull(), intervals: jsonb("intervals").notNull(),
}, (table) => [uniqueIndex("weather_forecast_identity_uidx").on(table.provider, table.sourceKey, table.fingerprint), index("weather_forecast_source_idx").on(table.provider, table.sourceKey, table.retrievedAt), check("weather_forecast_window_check", sql`${table.validFrom} < ${table.validThrough}`)]);

export const weatherOfficialAlertSnapshot = pgTable("weather_official_alert_snapshot", {
  id: uuid("id").defaultRandom().primaryKey(), provider: text("provider").notNull(), providerAlertId: text("provider_alert_id").notNull(), event: text("event").notNull(), status: text("status").notNull(), messageType: text("message_type").notNull(), sentAt: timestamp("sent_at", { withTimezone: true }).notNull(), effectiveAt: timestamp("effective_at", { withTimezone: true }).notNull(), onsetAt: timestamp("onset_at", { withTimezone: true }), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), endsAt: timestamp("ends_at", { withTimezone: true }), retrievedAt: timestamp("retrieved_at", { withTimezone: true }).notNull(), cancelled: boolean("cancelled").default(false).notNull(), headline: text("headline"), sourceUrl: text("source_url").notNull(), areaDescription: text("area_description").notNull(),
}, (table) => [uniqueIndex("weather_official_alert_identity_uidx").on(table.provider, table.providerAlertId, table.sentAt), index("weather_official_alert_expiry_idx").on(table.provider, table.expiresAt)]);

export const weatherOfficialAlertGarden = pgTable("weather_official_alert_garden", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: text("organization_id").notNull().references(() => organization.id, { onDelete: "cascade" }), gardenId: uuid("garden_id").notNull(), alertSnapshotId: uuid("alert_snapshot_id").notNull().references(() => weatherOfficialAlertSnapshot.id, { onDelete: "restrict" }), matchedAt: timestamp("matched_at", { withTimezone: true }).notNull(),
}, (table) => [uniqueIndex("weather_official_alert_garden_uidx").on(table.gardenId, table.alertSnapshotId), uniqueIndex("weather_official_alert_garden_tenant_key").on(table.organizationId, table.id), foreignKey({ columns: [table.organizationId, table.gardenId], foreignColumns: [garden.organizationId, garden.id], name: "weather_official_alert_garden_tenant_garden_fk" }).onDelete("cascade"), pgPolicy("weather_official_alert_garden_tenant", { for: "all", to: "trestle_app", using: sql`${table.organizationId} = current_setting('app.organization_id', true)`, withCheck: sql`${table.organizationId} = current_setting('app.organization_id', true)` })]).enableRLS();

export const weatherEvaluation = pgTable("weather_evaluation", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: text("organization_id").notNull().references(() => organization.id, { onDelete: "cascade" }), gardenId: uuid("garden_id").notNull(), hazard: text("hazard").notNull(), groupKey: text("group_key").notNull(), status: text("status").notNull(), snapshotId: uuid("snapshot_id").references(() => weatherForecastSnapshot.id, { onDelete: "restrict" }), trace: jsonb("trace").notNull(), evaluatedAt: timestamp("evaluated_at", { withTimezone: true }).notNull(),
}, (table) => [uniqueIndex("weather_evaluation_tenant_key").on(table.organizationId, table.id), index("weather_evaluation_garden_idx").on(table.gardenId, table.evaluatedAt), foreignKey({ columns: [table.organizationId, table.gardenId], foreignColumns: [garden.organizationId, garden.id], name: "weather_evaluation_tenant_garden_fk" }).onDelete("cascade"), check("weather_evaluation_status_check", sql`${table.status} IN ('evaluated', 'insufficient_inputs', 'stale', 'unavailable')`), pgPolicy("weather_evaluation_tenant", { for: "all", to: "trestle_app", using: sql`${table.organizationId} = current_setting('app.organization_id', true)`, withCheck: sql`${table.organizationId} = current_setting('app.organization_id', true)` })]).enableRLS();

export const recommendationEpisode = pgTable("recommendation_episode", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: text("organization_id").notNull().references(() => organization.id, { onDelete: "cascade" }), gardenId: uuid("garden_id").notNull(), hazard: text("hazard").notNull(), groupKey: text("group_key").notNull(), status: text("status").notNull(), openedAt: timestamp("opened_at", { withTimezone: true }).notNull(), resolvedAt: timestamp("resolved_at", { withTimezone: true }),
}, (table) => [uniqueIndex("recommendation_episode_tenant_key").on(table.organizationId, table.id), index("recommendation_episode_garden_idx").on(table.gardenId, table.hazard, table.groupKey), foreignKey({ columns: [table.organizationId, table.gardenId], foreignColumns: [garden.organizationId, garden.id], name: "recommendation_episode_tenant_garden_fk" }).onDelete("cascade"), check("recommendation_episode_status_check", sql`${table.status} IN ('open', 'resolved')`), pgPolicy("recommendation_episode_tenant", { for: "all", to: "trestle_app", using: sql`${table.organizationId} = current_setting('app.organization_id', true)`, withCheck: sql`${table.organizationId} = current_setting('app.organization_id', true)` })]).enableRLS();

export const gardenRiskState = pgTable("garden_risk_state", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: text("organization_id").notNull().references(() => organization.id, { onDelete: "cascade" }), gardenId: uuid("garden_id").notNull(), hazard: text("hazard").notNull(), groupKey: text("group_key").notNull(), state: text("state").notNull(), episodeId: uuid("episode_id").references(() => recommendationEpisode.id, { onDelete: "restrict" }), actionFingerprint: text("action_fingerprint"), clearConfirmationCount: integer("clear_confirmation_count").default(0).notNull(), supportingSnapshotId: uuid("supporting_snapshot_id").references(() => weatherForecastSnapshot.id, { onDelete: "restrict" }), lastEvaluatedAt: timestamp("last_evaluated_at", { withTimezone: true }).notNull(), revision: integer("revision").default(1).notNull(),
}, (table) => [uniqueIndex("garden_risk_identity_uidx").on(table.gardenId, table.hazard, table.groupKey), uniqueIndex("garden_risk_tenant_key").on(table.organizationId, table.id), foreignKey({ columns: [table.organizationId, table.gardenId], foreignColumns: [garden.organizationId, garden.id], name: "garden_risk_tenant_garden_fk" }).onDelete("cascade"), check("garden_risk_state_check", sql`${table.state} IN ('unknown', 'clear', 'active', 'resolved')`), check("garden_risk_revision_check", sql`${table.revision} > 0`), pgPolicy("garden_risk_tenant", { for: "all", to: "trestle_app", using: sql`${table.organizationId} = current_setting('app.organization_id', true)`, withCheck: sql`${table.organizationId} = current_setting('app.organization_id', true)` })]).enableRLS();

export const recommendationVersion = pgTable("recommendation_version", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: text("organization_id").notNull().references(() => organization.id, { onDelete: "cascade" }), gardenId: uuid("garden_id").notNull(), episodeId: uuid("episode_id").notNull(), version: integer("version").notNull(), transitionKind: text("transition_kind").notNull(), action: text("action"), affectedIds: jsonb("affected_ids").default([]).notNull(), validFrom: timestamp("valid_from", { withTimezone: true }), validThrough: timestamp("valid_through", { withTimezone: true }), evaluationId: uuid("evaluation_id").notNull(), evidence: jsonb("evidence").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
}, (table) => [uniqueIndex("recommendation_version_uidx").on(table.episodeId, table.version), uniqueIndex("recommendation_version_tenant_key").on(table.organizationId, table.id), foreignKey({ columns: [table.organizationId, table.gardenId], foreignColumns: [garden.organizationId, garden.id], name: "recommendation_version_tenant_garden_fk" }).onDelete("cascade"), foreignKey({ columns: [table.organizationId, table.episodeId], foreignColumns: [recommendationEpisode.organizationId, recommendationEpisode.id], name: "recommendation_version_tenant_episode_fk" }).onDelete("restrict"), foreignKey({ columns: [table.organizationId, table.evaluationId], foreignColumns: [weatherEvaluation.organizationId, weatherEvaluation.id], name: "recommendation_version_tenant_evaluation_fk" }).onDelete("restrict"), check("recommendation_version_transition_check", sql`${table.transitionKind} IN ('warning', 'material_change', 'resolution', 'renewed_warning')`), pgPolicy("recommendation_version_tenant", { for: "all", to: "trestle_app", using: sql`${table.organizationId} = current_setting('app.organization_id', true)`, withCheck: sql`${table.organizationId} = current_setting('app.organization_id', true)` })]).enableRLS();

export const recommendationTransition = pgTable("recommendation_transition", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: text("organization_id").notNull().references(() => organization.id, { onDelete: "cascade" }), gardenId: uuid("garden_id").notNull(), episodeId: uuid("episode_id").notNull(), recommendationVersionId: uuid("recommendation_version_id").notNull(), semanticKey: text("semantic_key").notNull(), kind: text("kind").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
}, (table) => [uniqueIndex("recommendation_transition_semantic_uidx").on(table.semanticKey), uniqueIndex("recommendation_transition_tenant_key").on(table.organizationId, table.id), foreignKey({ columns: [table.organizationId, table.gardenId], foreignColumns: [garden.organizationId, garden.id], name: "recommendation_transition_tenant_garden_fk" }).onDelete("cascade"), foreignKey({ columns: [table.organizationId, table.episodeId], foreignColumns: [recommendationEpisode.organizationId, recommendationEpisode.id], name: "recommendation_transition_tenant_episode_fk" }).onDelete("restrict"), foreignKey({ columns: [table.organizationId, table.recommendationVersionId], foreignColumns: [recommendationVersion.organizationId, recommendationVersion.id], name: "recommendation_transition_tenant_version_fk" }).onDelete("restrict"), pgPolicy("recommendation_transition_tenant", { for: "all", to: "trestle_app", using: sql`${table.organizationId} = current_setting('app.organization_id', true)`, withCheck: sql`${table.organizationId} = current_setting('app.organization_id', true)` })]).enableRLS();
