import { sql } from "drizzle-orm";
import { check, foreignKey, index, integer, jsonb, pgPolicy, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { organization } from "./auth-schema.js";
import { bed } from "./bed-schema.js";
import { garden } from "./garden-schema.js";
import { gardenPlanVersion } from "./planning-schema.js";

export const planTask = pgTable("plan_task", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: text("organization_id").notNull().references(() => organization.id, { onDelete: "cascade" }), gardenId: uuid("garden_id").notNull(), planVersionId: uuid("plan_version_id").notNull(), selectionId: uuid("selection_id").notNull(), taskType: text("task_type").notNull(), windowStartLocalDate: text("window_start_local_date").notNull(), windowEndLocalDate: text("window_end_local_date").notNull(), dependsOnTaskIds: jsonb("depends_on_task_ids").default([]).notNull(), instruction: text("instruction").notNull(), origin: text("origin").default("plan").notNull(), sourceProgressEventId: uuid("source_progress_event_id"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [uniqueIndex("plan_task_tenant_key").on(table.organizationId, table.id), uniqueIndex("plan_task_source_event_uidx").on(table.sourceProgressEventId).where(sql`${table.sourceProgressEventId} IS NOT NULL`), index("plan_task_garden_window_idx").on(table.gardenId, table.windowStartLocalDate), foreignKey({ columns: [table.organizationId, table.gardenId], foreignColumns: [garden.organizationId, garden.id], name: "plan_task_tenant_garden_fk" }).onDelete("cascade"), foreignKey({ columns: [table.organizationId, table.planVersionId], foreignColumns: [gardenPlanVersion.organizationId, gardenPlanVersion.id], name: "plan_task_tenant_plan_fk" }).onDelete("cascade"), check("plan_task_type_check", sql`${table.taskType} IN ('sow', 'seed_start', 'transplant', 'harvest', 'care')`), check("plan_task_window_check", sql`${table.windowStartLocalDate} <= ${table.windowEndLocalDate}`), check("plan_task_origin_check", sql`${table.origin} IN ('plan', 'derived_actual')`), pgPolicy("plan_task_tenant", { for: "all", to: "trestle_app", using: sql`${table.organizationId} = current_setting('app.organization_id', true)`, withCheck: sql`${table.organizationId} = current_setting('app.organization_id', true)` })]).enableRLS();

export const taskStatusVersion = pgTable("task_status_version", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: text("organization_id").notNull().references(() => organization.id, { onDelete: "cascade" }), taskId: uuid("task_id").notNull(), revision: integer("revision").notNull(), state: text("state").notNull(), scheduledStartLocalDate: text("scheduled_start_local_date").notNull(), scheduledEndLocalDate: text("scheduled_end_local_date").notNull(), actualLocalDate: text("actual_local_date"), note: text("note"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [uniqueIndex("task_status_revision_uidx").on(table.taskId, table.revision), uniqueIndex("task_status_tenant_key").on(table.organizationId, table.id), foreignKey({ columns: [table.organizationId, table.taskId], foreignColumns: [planTask.organizationId, planTask.id], name: "task_status_tenant_task_fk" }).onDelete("cascade"), check("task_status_revision_check", sql`${table.revision} > 0`), check("task_status_state_check", sql`${table.state} IN ('planned', 'completed', 'postponed', 'skipped')`), check("task_status_window_check", sql`${table.scheduledStartLocalDate} <= ${table.scheduledEndLocalDate}`), pgPolicy("task_status_tenant", { for: "all", to: "trestle_app", using: sql`${table.organizationId} = current_setting('app.organization_id', true)`, withCheck: sql`${table.organizationId} = current_setting('app.organization_id', true)` })]).enableRLS();

export const gardenProgressEvent = pgTable("garden_progress_event", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: text("organization_id").notNull().references(() => organization.id, { onDelete: "cascade" }), gardenId: uuid("garden_id").notNull(), planVersionId: uuid("plan_version_id").notNull(), taskId: uuid("task_id"), selectionId: uuid("selection_id").notNull(), eventType: text("event_type").notNull(), occurredLocalDate: text("occurred_local_date").notNull(), bedId: uuid("bed_id"), position: jsonb("position"), supersedesEventId: uuid("supersedes_event_id"), note: text("note"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [uniqueIndex("garden_progress_tenant_key").on(table.organizationId, table.id), index("garden_progress_garden_date_idx").on(table.gardenId, table.occurredLocalDate), foreignKey({ columns: [table.organizationId, table.gardenId], foreignColumns: [garden.organizationId, garden.id], name: "garden_progress_tenant_garden_fk" }).onDelete("cascade"), foreignKey({ columns: [table.organizationId, table.planVersionId], foreignColumns: [gardenPlanVersion.organizationId, gardenPlanVersion.id], name: "garden_progress_tenant_plan_fk" }).onDelete("restrict"), foreignKey({ columns: [table.organizationId, table.taskId], foreignColumns: [planTask.organizationId, planTask.id], name: "garden_progress_tenant_task_fk" }).onDelete("restrict"), foreignKey({ columns: [table.organizationId, table.bedId], foreignColumns: [bed.organizationId, bed.id], name: "garden_progress_tenant_bed_fk" }).onDelete("restrict"), check("garden_progress_event_type_check", sql`${table.eventType} IN ('sown', 'emerged', 'transplanted', 'harvested', 'removed', 'task_completed', 'task_postponed', 'task_skipped', 'correction')`), pgPolicy("garden_progress_tenant", { for: "all", to: "trestle_app", using: sql`${table.organizationId} = current_setting('app.organization_id', true)`, withCheck: sql`${table.organizationId} = current_setting('app.organization_id', true)` })]).enableRLS();
