import type { BedGeometry, Garden, MetricPoint } from "@easygardenplan/contracts";
import { useEffect, useState } from "react";

const apiOrigin = (import.meta.env.VITE_API_ORIGIN as string | undefined)?.replace(/\/$/u, "") ?? "";
type SavedBed = { id: string; name: string; revision: number; geometry: BedGeometry; measurementProvenance: string; sunlight: Array<{ observedOn: string; hours: number | null; category: string }> };
const initialGeometry: BedGeometry = { outer: [{ x: 0, y: 0 }, { x: 3, y: 0 }, { x: 3, y: 2 }, { x: 0, y: 2 }], exclusions: [] };
const clone = (geometry: BedGeometry): BedGeometry => structuredClone(geometry);

async function call<T>(path: string, organizationId: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`${apiOrigin}${path}`, { ...init, credentials: "include", headers: { "content-type": "application/json", "x-trestle-tenant": organizationId, ...init?.headers } });
  const body = await response.json() as T & { message?: string; issues?: string[] };
  if (!response.ok) throw new Error(body.message ?? body.issues?.join("; ") ?? "The bed could not be saved");
  return body;
}

function RingFields(props: { label: string; ring: MetricPoint[]; change: (ring: MetricPoint[]) => void }) {
  return <fieldset className="rounded-xl border border-slate-200 p-4"><legend className="px-2 text-sm font-semibold">{props.label}</legend><div className="space-y-2">{props.ring.map((point, index) => <div className="grid grid-cols-[1fr_1fr_auto] gap-2" key={index}><label className="text-xs">X (m)<input aria-label={`${props.label} vertex ${index + 1} X`} className="mt-1 w-full rounded-lg border px-2 py-2" type="number" step="0.01" value={point.x} onChange={(event) => { const next = [...props.ring]; next[index] = { ...point, x: Number(event.target.value) }; props.change(next); }} /></label><label className="text-xs">Y (m)<input aria-label={`${props.label} vertex ${index + 1} Y`} className="mt-1 w-full rounded-lg border px-2 py-2" type="number" step="0.01" value={point.y} onChange={(event) => { const next = [...props.ring]; next[index] = { ...point, y: Number(event.target.value) }; props.change(next); }} /></label><button aria-label={`Delete ${props.label} vertex ${index + 1}`} className="mt-5 px-2 text-red-700" disabled={props.ring.length <= 3} onClick={() => props.change(props.ring.filter((_, item) => item !== index))} type="button">Delete</button></div>)}</div><button className="mt-3 text-sm font-semibold text-brand-500" onClick={() => { const last = props.ring.at(-1)!; props.change([...props.ring, { x: last.x + 1, y: last.y }]); }} type="button">Add vertex</button></fieldset>;
}

function Preview({ geometry }: { geometry: BedGeometry }) {
  const all = [geometry.outer, ...geometry.exclusions].flat(); const xs = all.map(({ x }) => x), ys = all.map(({ y }) => y); const minX = Math.min(...xs), maxX = Math.max(...xs), minY = Math.min(...ys), maxY = Math.max(...ys); const scale = Math.min(440 / Math.max(1, maxX - minX), 260 / Math.max(1, maxY - minY)); const points = (ring: MetricPoint[]) => ring.map(({ x, y }) => `${30 + (x - minX) * scale},${30 + (maxY - y) * scale}`).join(" ");
  return <svg aria-label="Metric bed preview" className="h-72 w-full rounded-xl border bg-white" role="img" viewBox="0 0 500 320"><polygon fill="#dcfce7" points={points(geometry.outer)} stroke="#166534" strokeWidth="3" />{geometry.exclusions.map((ring, index) => <polygon fill="white" key={index} points={points(ring)} stroke="#991b1b" strokeDasharray="6 4" strokeWidth="2" />)}</svg>;
}

export function BedEditor(props: { garden: Garden; organizationId: string }) {
  const [beds, setBeds] = useState<SavedBed[]>([]); const [selected, setSelected] = useState<SavedBed>(); const [name, setName] = useState("Main bed"); const [geometry, setGeometry] = useState<BedGeometry>(initialGeometry); const [past, setPast] = useState<BedGeometry[]>([]); const [future, setFuture] = useState<BedGeometry[]>([]); const [measurement, setMeasurement] = useState(""); const [message, setMessage] = useState<string>(); const [busy, setBusy] = useState(false);
  const load = async () => { const result = await call<{ beds: SavedBed[] }>(`/api/gardens/${props.garden.id}/beds`, props.organizationId); setBeds(result.beds); };
  useEffect(() => { void load(); }, [props.garden.id, props.organizationId]);
  const change = (next: BedGeometry) => { setPast([...past, clone(geometry)]); setGeometry(next); setFuture([]); };
  const choose = (bed: SavedBed) => { setSelected(bed); setName(bed.name); setGeometry(clone(bed.geometry)); setPast([]); setFuture([]); };
  const save = async () => { setBusy(true); setMessage(undefined); try { const path = selected ? `/api/gardens/${props.garden.id}/beds/${selected.id}` : `/api/gardens/${props.garden.id}/beds`; await call(path, props.organizationId, { method: selected ? "PUT" : "POST", body: JSON.stringify({ name, expectedRevision: selected?.revision ?? 0, geometry, transform: { anchor: { latitude: Number(props.garden.latitude), longitude: Number(props.garden.longitude) }, rotationRadians: 0, scale: 1, translationMeters: { x: 0, y: 0 }, projection: "local_equirectangular_v1" }, measurementProvenance: measurement ? "calibrated" : "measured", sunlight: [] }) }); await load(); setSelected(undefined); setMessage("Bed revision saved."); } catch (error) { setMessage(error instanceof Error ? error.message : "Bed could not be saved"); } finally { setBusy(false); } };
  const calibrate = () => { const measured = Number(measurement), [a, b] = geometry.outer; if (!a || !b || !(measured > 0)) return; const current = Math.hypot(b.x - a.x, b.y - a.y); if (!current) return; const ratio = measured / current; change({ outer: geometry.outer.map(({ x, y }) => ({ x: x * ratio, y: y * ratio })), exclusions: geometry.exclusions.map((ring) => ring.map(({ x, y }) => ({ x: x * ratio, y: y * ratio }))) }); };
  return <section className="card mt-8 p-8"><p className="eyebrow">Beds and measurements</p><h2 className="mt-2 text-3xl font-semibold">Draw your growing space</h2><p className="mt-2 text-slate-600">Coordinates are meters from the garden pin. The field editor is the keyboard-accessible source of truth; the diagram previews the same geometry.</p>
    {!props.garden.locationConfirmed ? <p className="mt-5 rounded-xl bg-amber-50 p-4 text-sm">Confirm the garden pin before saving beds.</p> : <div className="mt-6 grid gap-6 lg:grid-cols-2"><div className="space-y-4"><label className="block text-sm font-medium">Bed name<input className="mt-1 w-full rounded-xl border px-3 py-2" value={name} onChange={(event) => setName(event.target.value)} /></label><div className="flex gap-2"><button className="rounded-lg border px-3 py-2 text-sm" disabled={!past.length} onClick={() => { const previous = past.at(-1); if (!previous) return; setFuture([clone(geometry), ...future]); setGeometry(previous); setPast(past.slice(0, -1)); }} type="button">Undo</button><button className="rounded-lg border px-3 py-2 text-sm" disabled={!future.length} onClick={() => { const next = future[0]; if (!next) return; setPast([...past, clone(geometry)]); setGeometry(next); setFuture(future.slice(1)); }} type="button">Redo</button></div><RingFields label="Outer boundary" ring={geometry.outer} change={(outer) => change({ ...geometry, outer })} />{geometry.exclusions.map((ring, index) => <RingFields key={index} label={`Exclusion ${index + 1}`} ring={ring} change={(next) => change({ ...geometry, exclusions: geometry.exclusions.map((item, itemIndex) => itemIndex === index ? next : item) })} />)}<button className="text-sm font-semibold text-brand-500" onClick={() => change({ ...geometry, exclusions: [...geometry.exclusions, [{ x: 0.5, y: 0.5 }, { x: 1, y: 0.5 }, { x: 1, y: 1 }]] })} type="button">Add exclusion</button><div className="flex items-end gap-2"><label className="flex-1 text-sm font-medium">Measured first edge (meters)<input className="mt-1 w-full rounded-xl border px-3 py-2" min="0.01" step="0.01" type="number" value={measurement} onChange={(event) => setMeasurement(event.target.value)} /></label><button className="rounded-xl border px-4 py-2 font-semibold" onClick={calibrate} type="button">Apply measurement</button></div></div><div><Preview geometry={geometry} /><button className="button mt-4" disabled={busy} onClick={() => void save()} type="button">{busy ? "Saving…" : selected ? "Save new revision" : "Save bed"}</button>{message && <p aria-live="polite" className="mt-3 text-sm">{message}</p>}<h3 className="mt-7 font-semibold">Saved beds</h3><ul className="mt-2 space-y-2">{beds.map((bed) => <li className="flex items-center justify-between rounded-lg border p-3" key={bed.id}><button className="font-medium" onClick={() => choose(bed)} type="button">{bed.name} · revision {bed.revision}</button><a className="text-sm font-semibold text-brand-500" href={`${apiOrigin}/api/gardens/${props.garden.id}/beds/${bed.id}/print.svg`} target="_blank" rel="noreferrer">Print diagram</a></li>)}</ul></div></div>}
  </section>;
}
