import type { Garden } from "@easygardenplan/contracts";
import { useEffect, useMemo, useState } from "react";

const apiOrigin = (import.meta.env.VITE_API_ORIGIN as string | undefined)?.replace(/\/$/u, "") ?? "";
type Task = { id: string; selectionId: string; taskType: string; instruction: string; origin: string; planState: string; planVersion: number; status: { revision: number; state: string; scheduledStartLocalDate: string; scheduledEndLocalDate: string; actualLocalDate: string | null } };
type Progress = { id: string; taskId: string | null; selectionId: string; eventType: string; occurredLocalDate: string; note: string | null; supersedesEventId: string | null; geometryStatus: "not_recorded" | "inside_current_bed" | "outside_current_bed" | "bed_unavailable"; currentBedRevision: number | null };

async function request<T>(path: string, organizationId: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`${apiOrigin}${path}`, { ...init, credentials: "include", headers: { "content-type": "application/json", "x-trestle-tenant": organizationId, ...init?.headers } });
  const body = await response.json() as T & { message?: string; error?: string };
  if (!response.ok) throw new Error(body.message ?? body.error ?? "Garden progress could not be saved");
  return body;
}
function localToday(timezone: string | null): string { const parts = new Intl.DateTimeFormat("en-CA", { timeZone: timezone ?? "UTC", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(new Date()); return `${parts.find(({ type }) => type === "year")?.value}-${parts.find(({ type }) => type === "month")?.value}-${parts.find(({ type }) => type === "day")?.value}`; }
function addDays(value: string, days: number): string { const [year, month, day] = value.split("-").map(Number) as [number, number, number]; const date = new Date(Date.UTC(year, month - 1, day)); date.setUTCDate(date.getUTCDate() + days); return date.toISOString().slice(0, 10); }

export function GardenCalendar(props: { garden: Garden; organizationId: string }) {
  const [tasks, setTasks] = useState<Task[]>([]); const [events, setEvents] = useState<Progress[]>([]); const [message, setMessage] = useState<string>(); const [busy, setBusy] = useState(false);
  const [eventType, setEventType] = useState("sown"); const [eventDate, setEventDate] = useState(() => localToday(props.garden.timezone));
  const [correctionTarget, setCorrectionTarget] = useState<Progress>(); const [correctionDate, setCorrectionDate] = useState(""); const [correctionNote, setCorrectionNote] = useState("");
  const activeTasks = tasks.filter(({ planState }) => planState === "active"); const today = localToday(props.garden.timezone); const weekEnd = addDays(today, 6);
  const thisWeek = activeTasks.filter(({ status }) => status.state === "planned" || status.state === "postponed").filter(({ status }) => status.scheduledStartLocalDate <= weekEnd && status.scheduledEndLocalDate >= today); const selectedTask = activeTasks[0];
  const load = async () => { const [taskResult, eventResult] = await Promise.all([request<{ tasks: Task[] }>(`/api/gardens/${props.garden.id}/tasks`, props.organizationId), request<{ events: Progress[] }>(`/api/gardens/${props.garden.id}/progress`, props.organizationId)]); setTasks(taskResult.tasks); setEvents(eventResult.events); };
  useEffect(() => { const refresh = () => void load().catch((error: unknown) => setMessage(error instanceof Error ? error.message : "Calendar could not be loaded")); refresh(); window.addEventListener("garden-data-changed", refresh); return () => window.removeEventListener("garden-data-changed", refresh); }, [props.garden.id, props.organizationId]);
  const mutate = async (operation: () => Promise<void>) => { setBusy(true); setMessage(undefined); try { await operation(); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Progress could not be saved"); } finally { setBusy(false); } };
  const transition = (task: Task, state: "completed" | "postponed" | "skipped") => void mutate(async () => { const body = state === "postponed" ? { expectedRevision: task.status.revision, state, scheduledStartLocalDate: addDays(task.status.scheduledStartLocalDate, 7), scheduledEndLocalDate: addDays(task.status.scheduledEndLocalDate, 7), note: "Postponed one week" } : { expectedRevision: task.status.revision, state, actualLocalDate: today }; await request(`/api/gardens/${props.garden.id}/tasks/${task.id}/transition`, props.organizationId, { method: "POST", body: JSON.stringify(body) }); });
  const record = () => void mutate(async () => { if (!selectedTask) throw new Error("Activate a plan with a scheduled task first"); await request(`/api/gardens/${props.garden.id}/progress`, props.organizationId, { method: "POST", body: JSON.stringify({ taskId: selectedTask.id, selectionId: selectedTask.selectionId, eventType, occurredLocalDate: eventDate, note: "Recorded by gardener" }) }); });
  const beginCorrection = (event: Progress) => { setCorrectionTarget(event); setCorrectionDate(event.occurredLocalDate); setCorrectionNote(""); };
  const correct = () => void mutate(async () => {
    if (!correctionTarget) return;
    await request(`/api/gardens/${props.garden.id}/progress`, props.organizationId, { method: "POST", body: JSON.stringify({ taskId: correctionTarget.taskId, selectionId: correctionTarget.selectionId, eventType: "correction", occurredLocalDate: correctionDate, supersedesEventId: correctionTarget.id, note: correctionNote || `Corrected ${correctionTarget.eventType.replaceAll("_", " ")} record` }) });
    setCorrectionTarget(undefined); setCorrectionNote("");
  });
  const ordered = useMemo(() => [...activeTasks].sort((a, b) => a.status.scheduledStartLocalDate.localeCompare(b.status.scheduledStartLocalDate)), [activeTasks]);

  return <section className="card mt-8 p-8">
    <p className="eyebrow">Calendar and progress</p><h2 className="mt-2 text-3xl font-semibold">This week</h2>
    <p className="mt-2 text-slate-600">Dates use {props.garden.timezone ?? "the garden timezone"}. Baseline plan windows remain unchanged when work is postponed or completed.</p>
    {!activeTasks.length ? <p className="mt-5 rounded-xl bg-slate-50 p-4 text-sm">Activate a planting proposal to create calendar tasks.</p> : <>
      <h3 className="mt-6 font-semibold">Due through {weekEnd}</h3>{thisWeek.length ? <ul className="mt-2 space-y-2">{thisWeek.map((task) => <li key={task.id}>{task.instruction}</li>)}</ul> : <p className="mt-2 text-sm text-slate-600">Nothing is due this week.</p>}
      <h3 className="mt-6 font-semibold">Full calendar</h3><ul className="mt-2 space-y-3">{ordered.map((task) => <li className="rounded-xl border p-4" key={task.id}><p className="font-medium">{task.taskType.replaceAll("_", " ")} · {task.status.scheduledStartLocalDate} through {task.status.scheduledEndLocalDate}</p><p className="text-sm text-slate-600">{task.instruction} · {task.status.state}{task.origin === "derived_actual" ? " · recalculated from an actual event" : ""}</p>{task.status.state !== "completed" && task.status.state !== "skipped" && <div className="mt-3 flex flex-wrap gap-2"><button className="rounded-lg border px-3 py-2 text-sm" disabled={busy} onClick={() => transition(task, "completed")} type="button">Complete</button><button className="rounded-lg border px-3 py-2 text-sm" disabled={busy} onClick={() => transition(task, "postponed")} type="button">Postpone one week</button><button className="rounded-lg border px-3 py-2 text-sm" disabled={busy} onClick={() => transition(task, "skipped")} type="button">Skip</button></div>}</li>)}</ul>
      <fieldset className="mt-7 grid gap-3 rounded-xl bg-slate-50 p-4 md:grid-cols-3"><legend className="px-2 font-semibold">Record what happened</legend><label className="text-sm">Event<select aria-label="Progress event" className="mt-1 w-full rounded border p-2" value={eventType} onChange={(event) => setEventType(event.target.value)}><option value="sown">Sown</option><option value="emerged">Emerged</option><option value="transplanted">Transplanted</option><option value="harvested">Harvested</option><option value="removed">Removed</option></select></label><label className="text-sm">Local date<input aria-label="Progress date" className="mt-1 w-full rounded border p-2" type="date" value={eventDate} onChange={(event) => setEventDate(event.target.value)} /></label><button className="button self-end" disabled={busy} onClick={record} type="button">Record progress</button></fieldset>
    </>}
    {message && <p aria-live="polite" className="mt-4 text-sm">{message}</p>}
    <h3 className="mt-7 font-semibold">History</h3>{events.length ? <ol className="mt-2 space-y-2 text-sm">{events.map((event) => <li className="rounded-lg border border-slate-100 px-3 py-2" key={event.id}><div className="flex flex-wrap items-center justify-between gap-2"><span>{event.occurredLocalDate}: {event.eventType.replaceAll("_", " ")}{event.supersedesEventId ? " (correction)" : ""}</span>{!event.supersedesEventId && <button className="rounded-lg border px-3 py-1 font-medium" disabled={busy} onClick={() => beginCorrection(event)} type="button">Correct</button>}</div>{event.geometryStatus === "outside_current_bed" && <p className="mt-2 rounded bg-amber-50 p-2 text-amber-900">This recorded position falls outside bed revision {event.currentBedRevision}. Check the revised outline or add a correction.</p>}{event.geometryStatus === "bed_unavailable" && <p className="mt-2 rounded bg-amber-50 p-2 text-amber-900">The recorded bed position cannot be checked against the current outline.</p>}</li>)}</ol> : <p className="mt-2 text-sm text-slate-600">No actual events recorded yet.</p>}
    {correctionTarget && <fieldset className="mt-5 grid gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 md:grid-cols-3"><legend className="px-2 font-semibold">Correct the {correctionTarget.eventType.replaceAll("_", " ")} record</legend><p className="text-sm text-amber-900">The original stays in history and this correction points to it.</p><label className="text-sm">Correct local date<input aria-label="Correction date" className="mt-1 w-full rounded border p-2" type="date" value={correctionDate} onChange={(event) => setCorrectionDate(event.target.value)} /></label><label className="text-sm">Reason<input aria-label="Correction reason" className="mt-1 w-full rounded border p-2" value={correctionNote} onChange={(event) => setCorrectionNote(event.target.value)} /></label><div className="flex gap-2 md:col-span-3"><button className="button" disabled={busy || !correctionDate} onClick={correct} type="button">Save correction</button><button className="rounded-xl border px-4 py-2 font-semibold" disabled={busy} onClick={() => setCorrectionTarget(undefined)} type="button">Cancel</button></div></fieldset>}
  </section>;
}
