import type { Garden, MetricPoint } from "@easygardenplan/contracts";
import { useEffect, useMemo, useState } from "react";

const apiOrigin = (import.meta.env.VITE_API_ORIGIN as string | undefined)?.replace(/\/$/u, "") ?? "";
type Crop = { id: string; commonName: string; scientificName: string | null };
type Bed = { id: string; name: string };
type Selection = { id: string; cropId: string; method: "direct_sow" | "indoor_start" | "purchased_start"; quantity: number; preferredBedId: string | null; bedRestriction: "soft" | "only"; priority: number; revision: number };
type Plan = { id: string; version: number; state: string; result: { placements: Array<{ id: string; selectionId: string; bedId: string; position: MetricPoint; pinned: boolean }>; selections: Array<{ selectionId: string; requested: number; placed: number; unplaced: number; reasonCodes: string[] }>; scheduleWindows: Array<{ selectionId: string; startLocalDate: string; endLocalDate: string; semantics: string }>; ruleSelectionTrace: Array<{ selectionId: string; ruleType: string; candidates: Array<{ ruleVersionId: string; outcome: string; reason: string }> }>; unresolved: Array<{ selectionId: string; kind: string; code: string }> } };

async function request<T>(path: string, organizationId: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`${apiOrigin}${path}`, { ...init, credentials: "include", headers: { "content-type": "application/json", "x-trestle-tenant": organizationId, ...init?.headers } });
  const body = await response.json() as T & { message?: string; error?: string };
  if (!response.ok) throw new Error(body.message ?? body.error ?? "The plan could not be updated");
  return body;
}
const limitationKey = (item: Plan["result"]["unresolved"][number]) => `${item.kind}:${item.selectionId}:${item.code}`;

export function PlanBuilder(props: { garden: Garden; organizationId: string }) {
  const [crops, setCrops] = useState<Crop[]>([]); const [beds, setBeds] = useState<Bed[]>([]); const [selections, setSelections] = useState<Selection[]>([]); const [plans, setPlans] = useState<Plan[]>([]); const [cropId, setCropId] = useState(""); const [method, setMethod] = useState<Selection["method"]>("direct_sow"); const [quantity, setQuantity] = useState(4); const [preferredBedId, setPreferredBedId] = useState(""); const [restriction, setRestriction] = useState<Selection["bedRestriction"]>("soft"); const [acknowledged, setAcknowledged] = useState<string[]>([]); const [message, setMessage] = useState<string>(); const [busy, setBusy] = useState(false); const [adjust, setAdjust] = useState<{ placementId: string; bedId: string; x: number; y: number }>();
  const current = plans.find(({ state }) => state === "proposal") ?? plans.find(({ state }) => state === "active") ?? plans[0];
  const cropNames = useMemo(() => new Map(crops.map((crop) => [crop.id, crop.commonName])), [crops]);
  const load = async () => { const [catalog, bedResult, selectionResult, planResult] = await Promise.all([request<{ crops: Crop[] }>("/api/catalog", props.organizationId), request<{ beds: Bed[] }>(`/api/gardens/${props.garden.id}/beds`, props.organizationId), request<{ selections: Selection[] }>(`/api/gardens/${props.garden.id}/selections`, props.organizationId), request<{ plans: Plan[] }>(`/api/gardens/${props.garden.id}/plans`, props.organizationId)]); setCrops(catalog.crops); setBeds(bedResult.beds); setSelections(selectionResult.selections); setPlans(planResult.plans); setCropId((value) => value || catalog.crops[0]?.id || ""); setPreferredBedId((value) => value || bedResult.beds[0]?.id || ""); };
  useEffect(() => { void load().catch((error: unknown) => setMessage(error instanceof Error ? error.message : "Planning data could not be loaded")); }, [props.garden.id, props.organizationId]);
  const work = async (operation: () => Promise<void>) => { setBusy(true); setMessage(undefined); try { await operation(); await load(); window.dispatchEvent(new Event("garden-data-changed")); } catch (error) { setMessage(error instanceof Error ? error.message : "The plan could not be updated"); } finally { setBusy(false); } };
  const add = () => void work(async () => { if (!cropId) throw new Error("No published crops are available yet"); await request(`/api/gardens/${props.garden.id}/selections`, props.organizationId, { method: "POST", body: JSON.stringify({ cropId, varietyId: null, method, quantity, preferredBedId: preferredBedId || null, bedRestriction: restriction, priority: selections.length, expectedRevision: 0 }) }); setMessage("Crop added."); });
  const generate = () => void work(async () => { await request(`/api/gardens/${props.garden.id}/plans`, props.organizationId, { method: "POST", body: JSON.stringify({ seasonYear: new Date().getFullYear() }) }); setAcknowledged([]); });
  const activate = () => void work(async () => { if (!current) return; await request(`/api/gardens/${props.garden.id}/plans/${current.id}/activate`, props.organizationId, { method: "POST", body: JSON.stringify({ acknowledgedLimitations: acknowledged }) }); });
  const move = () => void work(async () => { if (!current || !adjust) return; await request(`/api/gardens/${props.garden.id}/plans/${current.id}/adjust`, props.organizationId, { method: "POST", body: JSON.stringify({ placementId: adjust.placementId, bedId: adjust.bedId, position: { x: adjust.x, y: adjust.y } }) }); });
  useEffect(() => { const placement = current?.result.placements[0]; if (placement) setAdjust({ placementId: placement.id, bedId: placement.bedId, x: placement.position.x, y: placement.position.y }); }, [current?.id]);

  return <section className="card mt-8 p-8"><p className="eyebrow">Crops and plan</p><h2 className="mt-2 text-3xl font-semibold">Build a planting proposal</h2><p className="mt-2 text-slate-600">Every proposal freezes the exact garden, climate, catalog, and bed revisions used to calculate it.</p>
    {!crops.length ? <p className="mt-5 rounded-xl bg-amber-50 p-4 text-sm">The reviewed crop catalog is empty. Editorial publication must finish before customer plans can be generated.</p> : <div className="mt-6 grid gap-3 md:grid-cols-5"><label className="text-sm font-medium">Crop<select aria-label="Crop" className="mt-1 w-full rounded-lg border p-2" value={cropId} onChange={(event) => setCropId(event.target.value)}>{crops.map((crop) => <option key={crop.id} value={crop.id}>{crop.commonName}</option>)}</select></label><label className="text-sm font-medium">Method<select aria-label="Growing method" className="mt-1 w-full rounded-lg border p-2" value={method} onChange={(event) => setMethod(event.target.value as Selection["method"])}><option value="direct_sow">Direct sow</option><option value="indoor_start">Start indoors</option><option value="purchased_start">Purchased start</option></select></label><label className="text-sm font-medium">Retained plants<input aria-label="Retained plants" className="mt-1 w-full rounded-lg border p-2" min="1" max="1000" type="number" value={quantity} onChange={(event) => setQuantity(Number(event.target.value))} /></label><label className="text-sm font-medium">Preferred bed<select aria-label="Preferred bed" className="mt-1 w-full rounded-lg border p-2" value={preferredBedId} onChange={(event) => setPreferredBedId(event.target.value)}><option value="">No preference</option>{beds.map((bed) => <option key={bed.id} value={bed.id}>{bed.name}</option>)}</select></label><label className="text-sm font-medium">Preference<select aria-label="Bed preference" className="mt-1 w-full rounded-lg border p-2" value={restriction} onChange={(event) => setRestriction(event.target.value as Selection["bedRestriction"])}><option value="soft">Prefer</option><option value="only">Only this bed</option></select></label><button className="button md:col-span-2" disabled={busy || !beds.length} onClick={add} type="button">Add crop</button></div>}
    <ul className="mt-5 space-y-2">{selections.map((selection) => <li className="rounded-lg border p-3 text-sm" key={selection.id}>{cropNames.get(selection.cropId) ?? "Published crop"}: {selection.quantity} retained plants · {selection.method.replaceAll("_", " ")}</li>)}</ul>
    <button className="button mt-5" disabled={busy || !selections.length || !beds.length} onClick={generate} type="button">Generate proposal</button>
    {message && <p aria-live="polite" className="mt-4 rounded-lg bg-slate-50 p-3 text-sm">{message}</p>}
    {current && <div className="mt-7 rounded-xl border p-5"><h3 className="text-xl font-semibold">Plan version {current.version} · {current.state}</h3><ul className="mt-3 space-y-2">{current.result.selections.map((result) => <li key={result.selectionId}>{cropNames.get(selections.find(({ id }) => id === result.selectionId)?.cropId ?? "") ?? "Crop"}: {result.placed} placed, {result.unplaced} unplaced{result.reasonCodes.length ? ` (${result.reasonCodes.join(", ")})` : ""}</li>)}</ul><h4 className="mt-5 font-semibold">Planting windows</h4>{current.result.scheduleWindows.length ? <ul>{current.result.scheduleWindows.map((window, index) => <li key={`${window.selectionId}-${index}`}>{window.startLocalDate} through {window.endLocalDate}</li>)}</ul> : <p className="text-sm text-slate-600">No dated window can be claimed from the current reviewed inputs.</p>}<details className="mt-5"><summary className="cursor-pointer font-semibold">Why these rules were used</summary><ul className="mt-2 space-y-1 text-xs text-slate-600">{current.result.ruleSelectionTrace.flatMap((trace) => trace.candidates.map((candidate) => <li key={`${trace.selectionId}:${trace.ruleType}:${candidate.ruleVersionId}`}>{trace.ruleType}: {candidate.outcome.replaceAll("_", " ")} ({candidate.reason.replaceAll("_", " ")})</li>))}</ul></details>
      {adjust && <fieldset className="mt-5 grid gap-2 rounded-lg bg-slate-50 p-4 md:grid-cols-4"><legend className="px-2 font-semibold">Pin the first placement</legend><label className="text-sm">X (m)<input aria-label="Pinned placement X" className="mt-1 w-full rounded border p-2" type="number" step="0.01" value={adjust.x} onChange={(event) => setAdjust({ ...adjust, x: Number(event.target.value) })} /></label><label className="text-sm">Y (m)<input aria-label="Pinned placement Y" className="mt-1 w-full rounded border p-2" type="number" step="0.01" value={adjust.y} onChange={(event) => setAdjust({ ...adjust, y: Number(event.target.value) })} /></label><label className="text-sm">Bed<select aria-label="Pinned placement bed" className="mt-1 w-full rounded border p-2" value={adjust.bedId} onChange={(event) => setAdjust({ ...adjust, bedId: event.target.value })}>{beds.map((bed) => <option key={bed.id} value={bed.id}>{bed.name}</option>)}</select></label><button className="rounded-lg border px-3 py-2 font-semibold" disabled={busy} onClick={move} type="button">Save pinned position</button></fieldset>}
      {current.result.unresolved.length > 0 && <fieldset className="mt-5"><legend className="font-semibold">Limitations to acknowledge</legend>{current.result.unresolved.map((item) => { const key = limitationKey(item); return <label className="mt-2 flex gap-2 text-sm" key={key}><input aria-label={`Acknowledge ${item.code}`} checked={acknowledged.includes(key)} onChange={(event) => setAcknowledged(event.target.checked ? [...acknowledged, key] : acknowledged.filter((value) => value !== key))} type="checkbox" />{item.kind}: {item.code.replaceAll("_", " ")}</label>; })}</fieldset>}
      <a className="ml-3 mt-5 inline-block font-semibold text-brand-500" href={`${apiOrigin}/api/gardens/${props.garden.id}/plans/${current.id}/print.svg`} rel="noreferrer" target="_blank">Print staking plan</a>{current.state === "proposal" && <button className="button mt-5" disabled={busy || acknowledged.length < current.result.unresolved.length} onClick={activate} type="button">Activate this plan</button>}
    </div>}
  </section>;
}
