import type { Garden } from "@easygardenplan/contracts";
import { useEffect, useState } from "react";

const apiOrigin = (import.meta.env.VITE_API_ORIGIN as string | undefined)?.replace(/\/$/u, "") ?? "";
type Risk = { id: string; hazard: string; groupKey: string; state: "unknown" | "clear" | "active" | "resolved"; lastEvaluatedAt: string; revision: number };
type Recommendation = { id: string; transitionKind: "warning" | "material_change" | "resolution" | "renewed_warning"; action: string | null; affectedIds: string[]; validFrom: string | null; validThrough: string | null; createdAt: string };
async function request<T>(path: string, organizationId: string, init?: RequestInit): Promise<T> { const response = await fetch(`${apiOrigin}${path}`, { ...init, credentials: "include", headers: { "content-type": "application/json", "x-trestle-tenant": organizationId, ...init?.headers } }); const body = await response.json() as T & { message?: string; error?: string }; if (!response.ok) throw new Error(body.message ?? body.error ?? "Weather monitoring is unavailable"); return body; }

export function WeatherMonitoring(props: { garden: Garden; organizationId: string }) {
  const [risk, setRisk] = useState<Risk[]>([]); const [recommendations, setRecommendations] = useState<Recommendation[]>([]); const [message, setMessage] = useState<string>(); const [busy, setBusy] = useState(false);
  const load = async () => { const result = await request<{ risk: Risk[]; recommendations: Recommendation[] }>(`/api/gardens/${props.garden.id}/monitoring`, props.organizationId); setRisk(result.risk); setRecommendations(result.recommendations); };
  useEffect(() => { void load().catch((error: unknown) => setMessage(error instanceof Error ? error.message : "Weather history could not be loaded")); }, [props.garden.id, props.organizationId]);
  const refresh = async () => { setBusy(true); setMessage(undefined); try { await request(`/api/gardens/${props.garden.id}/monitoring/evaluations`, props.organizationId, { method: "POST", body: "{}" }); setMessage("A fresh evaluation is queued. The page will show it after weather processing completes."); } catch (error) { setMessage(error instanceof Error ? error.message : "Weather monitoring is unavailable"); } finally { setBusy(false); } };
  const current = recommendations[0];
  return <section className="card mt-8 p-8"><p className="eyebrow">Weather</p><h2 className="mt-2 text-3xl font-semibold">Forecast-aware guidance</h2><p className="mt-2 text-slate-600">Your seasonal plan remains useful without live weather. Check your local forecast before planting and protect sensitive plants when their reviewed guidance calls for it. Record what actually happens so later dates stay grounded in your garden.</p>{!props.garden.monitoringEnabled ? <p className="mt-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-900">Turn on weather monitoring in Garden basics to prepare this garden for Pro updates.</p> : <div className="mt-5"><button className="button" disabled={busy} onClick={() => void refresh()} type="button">{busy ? "Requesting…" : "Check for a weather update"}</button></div>}{message && <p aria-live="polite" className="mt-4 text-sm">{message}</p>}<h3 className="mt-7 font-semibold">Current monitoring state</h3>{risk.length ? <ul className="mt-2 space-y-2">{risk.map((item) => <li className="rounded-xl border p-3" key={item.id}><strong>{item.hazard.replaceAll("_", " ")}: {item.state}</strong><span className="block text-sm text-slate-600">Last evaluated {new Date(item.lastEvaluatedAt).toLocaleString()}</span></li>)}</ul> : <p className="mt-2 text-sm text-slate-600">No crop-specific weather evaluation has completed yet.</p>}<h3 className="mt-7 font-semibold">Latest recommendation</h3>{current ? <article className={`mt-2 rounded-xl p-4 ${current.transitionKind === "resolution" ? "bg-emerald-50" : "bg-amber-50"}`}><p className="font-medium">{current.transitionKind.replaceAll("_", " ")}</p><p className="mt-1 text-sm">{current.action}</p>{current.validFrom && <p className="mt-2 text-xs text-slate-600">Relevant from {new Date(current.validFrom).toLocaleString()} through {new Date(current.validThrough!).toLocaleString()}</p>}</article> : <p className="mt-2 text-sm text-slate-600">There are no weather recommendations in this garden’s history.</p>}</section>;
}
