import { z } from "zod";
import { bedGeometrySchema, metricPointSchema } from "./geometry.js";
import { growingMethodSchema, publishedRuleSchema } from "./knowledge.js";
import { monthDaySchema } from "./location.js";

export const cropSelectionSchema = z.object({ id: z.string().uuid(), cropId: z.string().uuid(), varietyId: z.string().uuid().nullable(), method: growingMethodSchema, quantity: z.number().int().positive().max(1000), preferredBedId: z.string().uuid().nullable(), bedRestriction: z.enum(["soft", "only"]).default("soft"), priority: z.number().int().default(0), revision: z.number().int().positive().default(1) });
export const planningBedSchema = z.object({ id: z.string().uuid(), revisionId: z.string().uuid(), revision: z.number().int().positive(), geometry: bedGeometrySchema });
export const planningClimateSchema = z.object({ associationId: z.string().uuid(), version: z.number().int().positive(), state: z.enum(["known", "frost_free", "unknown", "uncertain"]), hardinessZone: z.string().nullable(), springFrostLocalDate: monthDaySchema.nullable(), autumnFrostLocalDate: monthDaySchema.nullable(), source: z.string().min(1) });
export const planInputSnapshotSchema = z.object({ gardenId: z.string().uuid(), gardenRevision: z.number().int().positive(), timezone: z.string().min(1), seasonYear: z.number().int().min(2000).max(2200), catalogReleaseId: z.string().uuid(), climate: planningClimateSchema.nullable(), algorithmVersion: z.literal("grid-v1"), selections: z.array(cropSelectionSchema), beds: z.array(planningBedSchema), rules: z.array(publishedRuleSchema) });
export const planPlacementSchema = z.object({ id: z.string(), selectionId: z.string().uuid(), cropId: z.string().uuid(), bedId: z.string().uuid(), position: metricPointSchema, footprintRadiusMeters: z.number().positive(), spacingRuleVersionId: z.string().uuid(), pinned: z.boolean() });
export const planSelectionResultSchema = z.object({ selectionId: z.string().uuid(), requested: z.number().int().nonnegative(), placed: z.number().int().nonnegative(), unplaced: z.number().int().nonnegative(), reasonCodes: z.array(z.enum(["missing_spacing_rule", "conflicting_spacing_rules", "invalid_geometry", "no_eligible_bed", "layout_search_exhausted", "search_budget_exhausted"])) });
export const scheduleWindowSchema = z.object({ selectionId: z.string().uuid(), ruleVersionId: z.string().uuid(), startLocalDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/u), endLocalDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/u), semantics: z.string().min(1) });
export const ruleSelectionTraceSchema = z.object({ selectionId: z.string().uuid(), ruleType: z.enum(["spacing", "planting_window"]), candidates: z.array(z.object({ ruleVersionId: z.string().uuid(), outcome: z.enum(["selected", "overridden", "not_applicable", "conflicting"]), reason: z.string().min(1) })) });
export const planResultSchema = z.object({ algorithmVersion: z.literal("grid-v1"), fingerprint: z.string().regex(/^[a-f0-9]{64}$/u), placements: z.array(planPlacementSchema), selections: z.array(planSelectionResultSchema), scheduleWindows: z.array(scheduleWindowSchema), ruleVersionIds: z.array(z.string().uuid()), ruleSelectionTrace: z.array(ruleSelectionTraceSchema).default([]), unresolved: z.array(z.object({ selectionId: z.string().uuid(), kind: z.enum(["placement", "schedule"]), code: z.string() })) });
export type CropSelection = z.infer<typeof cropSelectionSchema>;
export type PlanInputSnapshot = z.infer<typeof planInputSnapshotSchema>;
export type PlanResult = z.infer<typeof planResultSchema>;
